client_config_backend: file
client_config_file: ../credentials.json

save_credentials: True
save_credentials_backend: file
save_credentials_file: ../credentials.txt

get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/drive.install